language: c

env:
  global:
    - LUAROCKS_BASE=2.2.0
    - ROCKSPEC=slingshot-git-1.rockspec
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  # Put back the links for libyaml, which are missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;
  - sudo apt-get install help2man
  - bash .travis/setup_lua.sh

install:
  # Install extra rocks into $LUAROCKS_CONFIG rocks tree.
  - sudo luarocks install lyaml; sudo luarocks install specl;

  # Make git rockspec
  - make rockspecs V=1
    || cat $ROCKSPEC

  - sudo luarocks make $ROCKSPEC LUA="$LUA"

script:
  - make check V=1

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
